name: Scheduled Trigger Go CI

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight for UTC

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
        check-latest: true
        cache: true

    - name: Install dependencies and build
      run: |
        go mod download -x
        go build -o crawler crawler.go

    - name: Run
      run: |
        go run .

    - name: Deploy
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        commit_message: "upd: Kvkk data updated"
        file_pattern: "*.json"